### ISSUE TITLE
Remove Cruft

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#1]
This code was originally imported from a blogger site. There is a lot of extra markup that can be removed from these files without impacting functionality. It would be amazing if someone could spend some time going through the [`index.html`](https://github.com/abamath/abamath.com/blob/master/index.html) file and remove lines (classes, JavaScript, blogger tags) that are no longer relevant.

**Comment by Jdtanacredi** [comment]
I'll take a swing at this tomorrow

**Comment by LukeSchlangen** [comment]
Sounds great! Thank you! There is a lot in there so even cleaning up a portion of it would be greatly appreciated!

**Comment by Lysautumn** [comment]
I can also help out with this, I will start at the bottom and comment where I stop so we're not doing the same work, @Jdtanacredi

**Comment by LukeSchlangen** [comment]
Thank you! If you make small Pull Requests, I will try to stay on top of approving and merging them in to avoid conflicts!

**Comment by LukeSchlangen** [comment]
Thank you @Jdtanacredi @sketchet and @nymarya for getting things started! I'm going to leave this open since there's still a decent amount of extra tags I don't think are necessary.

**Comment by Jdtanacredi** [comment]
Sounds good!

Tomorrow I'll remove the duplicated scripts folder and add the images referenced in the css folder locally, unless someone else ends up getting to that today 😃

**Comment by LukeSchlangen** [comment]
Thank you @Jdtanacredi ! I'm trying to practice my merging/github/open source collaboration skills and somehow I duplicated the folder! Thank you for catching that!

**Comment by LukeSchlangen** [comment]
Fixed by #35
