### ISSUE TITLE
Optimize and possibly change out images

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#13]
These images have been the same for several years. I like that they are specific to abamath, but it might be valuable to replace them with higher-quality images from a source like [unsplash.com](unsplash.com). I have included a few that I like.

Regardless of whether we keep the images or replace them, the final images should be compressed. Steps for how to do that are available here:
https://developers.google.com/speed/docs/insights/OptimizeImages

![website-design](https://user-images.githubusercontent.com/5384581/31506047-fc2ddbd0-af3b-11e7-8310-c7c5c06959c1.jpg)
![video-game-creation](https://user-images.githubusercontent.com/5384581/31506048-fc3a49b0-af3b-11e7-8f88-97e4b0f9da5a.jpg)
![website-creation-for-kids](https://user-images.githubusercontent.com/5384581/31506049-fc55cf8c-af3b-11e7-9208-edae5541c053.jpg)
![video-game-creation-for-kids](https://user-images.githubusercontent.com/5384581/31506050-fc650010-af3b-11e7-88f8-769ae91e2a08.jpg)
![computer-coding-for-kids](https://user-images.githubusercontent.com/5384581/31506051-fc70e36c-af3b-11e7-9f62-5dbf4a266529.jpg)
![computer-coders](https://user-images.githubusercontent.com/5384581/31506052-fca02f1e-af3b-11e7-816c-abe71ad32f32.jpg)

**Comment by ungps** [comment]
Trying now. :D

**Comment by k4vglitcher** [comment]
Is it fine to replace with images not included above? Might want to also keep some original images, but of course compressed

**Comment by LukeSchlangen** [comment]
Yes! I'm open to replacing with other images and even resizing the images, but I'll admit that will make my approval a little more subjective. Thanks @ungps for compressing the new ones with #14 !

**Comment by LukeSchlangen** [comment]
I've gotten help from a few people now! Seems like this is good to go for now! This took us from mid-60s to 70/100 on google insights! Thanks everybody! We're inching our way to a better site!

<img width="1280" alt="screen shot 2017-10-12 at 9 13 51 pm" src="https://user-images.githubusercontent.com/5384581/31527383-64ab664a-af92-11e7-9f56-923664167de5.png">
