### ISSUE TITLE
Remove random hyperlink underline by navbar logo

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#17]
The navbar has a random orange underline showing up next to it when I hover over the logo (see pictures). I would like to get rid of that effect. I’m sure it’s some rogue css, so if a brave soul would like to track that down and wipe out some of the extra css that exists in the process, I would greatly appreciate it.

<img width="1017" alt="screen shot 2017-10-12 at 5 43 01 pm" src="https://user-images.githubusercontent.com/5384581/31523106-3ce936de-af77-11e7-9994-e62fbe503c30.png">

<img width="1019" alt="screen shot 2017-10-12 at 5 43 15 pm" src="https://user-images.githubusercontent.com/5384581/31523108-40ebeb32-af77-11e7-823e-9f4b71cc1e8d.png">

**Comment by Ceciceciceci** [comment]
Hello I think I found why there's a dashline by the logo. I can try making a pull request and you can check it out!

**Comment by LukeSchlangen** [comment]
Huge thank you to @Ceciceciceci!
