### ISSUE TITLE
Move scripts to local repository

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#2]
The scripts in the [`index.html`](https://github.com/abamath/abamath.com/blob/master/index.html) file are currently brought in from all over the web through various `cdn`s and other projects. These should be brought into the local project to reduce the complexity of these requests and eventually allow minimization.

**Comment by Jdtanacredi** [comment]
I can help with this too. I also noticed all of the styles and functionality are within the main index.html file, would you like me to break this up a bit?

**Comment by LukeSchlangen** [comment]
That would be great! I'd love to move the JavaScript to a more sensible location like a `scripts` folder!

**Comment by LukeSchlangen** [comment]
Done! Thank you @nymarya and @Jdtanacredi !
