### ISSUE TITLE
CSS consolidation

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#20]
I know that this is overkill and I think it is hurting the site on load. I would love to reduce these four files to just two (probably keeping bootstrap and one other), and even better would be removing lines from the css files that are unused or can be refactored.

```
<link href='./public/css/bootstrap.min.css' rel='stylesheet'/>
<link href='./public/css/blogger-css-bundle.css' rel='stylesheet'/>
<link href='./public/css/page-skin-1.css' rel='stylesheet'/>
<link href='./public/css/template-skin-1.css' rel='stylesheet'/>
```

**Comment by maria-mata** [comment]
I can help! Will fork now 🙂

**Comment by LukeSchlangen** [comment]
Thank you @maria-mata!
