### ISSUE TITLE
Mobile navbar styling broken, should be opaque

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#24]
The dropdown menu on mobile is broken. The background is transparent when it should be opaque white. It could have happened in the recent styling changes, but I'm not totally sure what the cause was.

<img width="563" alt="screen shot 2017-10-12 at 7 07 47 pm" src="https://user-images.githubusercontent.com/5384581/31524696-f4e67aa4-af80-11e7-9bf1-960c02f657b9.png">

**Comment by andrewbash** [comment]
I can take care of this.

**Comment by LukeSchlangen** [comment]
Thank you for digging into it!

**Comment by pbarnum** [comment]
Oops! I don't know the rules/etiquette of hacktoberfest. I've made a PR with a potential fix. @andrewbash don't hesitate to take a look and comment/fix/bash my work.

**Comment by LukeSchlangen** [comment]
Thank you both for taking a look at this @pbarnum and @andrewbash!

**Comment by andrewbash** [comment]
@pbarnum Oh, sorry - added a PR. I'll take a look at yours though!

Thanks @LukeSchlangen

**Comment by LukeSchlangen** [comment]
I accepted @pbarnum's because it was the first one I saw, but if there's a reason using the media query would be better, I'm definitely curious. Thanks @andrewbash!

**Comment by andrewbash** [comment]
@LukeSchlangen I think @pbarnum's solution is better. Didn't notice the height issue - but it is certainly cleaner to fix the root issue vs. refactoring the nav like I did :)
