### ISSUE TITLE
Fix README.md links to match with links on the site

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#28]
On abamath.com, there are links on some of the description "Tell us about yourself here!" and it would be nice to have those links show up on the README on github as well.

On Github, unlike on the site, it might also make sense to direct people to the issues tab if they are interested in getting involved. I link to this issues tab could be good.

For someone who might want to take this as a first issue, links is Markdown files (like README.md) are created like this

```Markdown
[The text that will appear](www.the-link-to-go-to.com)
```

**Comment by kodisto** [comment]
I'll take this on.

**Comment by LukeSchlangen** [comment]
Closed! Thank you @kodisto!
