### ISSUE TITLE
Angular flashes {{ }} template and shows (show more classes) for split second on load

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#29]
I've tried using ng-cloak to hide the flash of angular on the screen, but for some reason, I still get a brief moment of the template showing on the screen before it is replaced by the class list. Maybe the solution is upgrading to a newer version of angular, and that's ok, but I want to get rid of the flash that happens on page load.

Now if you're looking at the markup for the table, I'm sure you'll be rightly disgusted a little by the button tag spamming, that's there because without it, I couldn't get the site to work with safari on iPhone 4. You might be tempted to helpfully remove those since it will still work in most browsers, but unfortunately, I need to leave those in there.

**Comment by jbmills327** [comment]
@LukeSchlangen You mind if I take a crack at fixing the mustache flash?

**Comment by LukeSchlangen** [comment]
Please do! I always call them "double-curlies" or "wormholes", but I like that 😃

**Comment by jbmills327** [comment]
I like wormholes as well!

**Comment by jbmills327** [comment]
@LukeSchlangen I think I might have resolved the issue and submitted a PR.  Let me know if it works on your end, it seemed to for me.

**Comment by LukeSchlangen** [comment]
It looks great! Thank you so much!
