### ISSUE TITLE
Google PageSpeed Test Enhancements

### ISSUE THREAD

**Issue by LukeSchlangen** [abamath/abamath.com#3]
Any of the items on this list:
https://developers.google.com/speed/pagespeed/insights/?url=abamath.com&tab=mobile

Eliminate render-blocking JavaScript and CSS in above-the-fold content
Leverage browser caching
Optimize images
Minify JavaScript
Minify HTML

**Comment by nymarya** [comment]
Working on it

**Comment by LukeSchlangen** [comment]
Thank you! Since the `index.html` file is currently a pretty big mess, I think this could conflict with changes made in #1 and #2, so I think the smaller the Pull Request(s) can be broken down, the better!

**Comment by LukeSchlangen** [comment]
I'm going to break these out into smaller, clearer features.
